# Generated by Django 5.1.4 on 2025-03-04 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=40)),
                ('aerodrom', models.CharField(max_length=60)),
                ('drzava', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Let',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vreme', models.DateTimeField()),
                ('do', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='do', to='glavna.grad')),
                ('od', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='od', to='glavna.grad')),
            ],
        ),
    ]
