# Generated by Django 5.1.4 on 2025-03-07 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glavna', '0002_karta'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipKarte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PreostaloKarata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preostalo', models.PositiveIntegerField()),
                ('cena', models.DecimalField(decimal_places=2, default=5000.0, max_digits=7)),
                ('let', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='glavna.let')),
                ('tip_karte', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='glavna.tipkarte')),
            ],
        ),
        migrations.DeleteModel(
            name='Karta',
        ),
    ]
