# Generated by Django 5.1.4 on 2025-03-07 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glavna', '0003_tipkarte_preostalokarata_delete_karta'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipkarte',
            name='dodusl',
            field=models.CharField(default='/', max_length=100),
        ),
        migrations.AddField(
            model_name='tipkarte',
            name='prtljag',
            field=models.CharField(default='ranac', max_length=100),
        ),
        migrations.AlterField(
            model_name='tipkarte',
            name='naziv',
            field=models.CharField(max_length=30),
        ),
    ]
