# Generated by Django 5.1.4 on 2025-03-13 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glavna', '0004_tipkarte_dodusl_tipkarte_prtljag_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KupljenaKarta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena', models.DecimalField(decimal_places=2, default=5000.0, max_digits=7)),
                ('kupac', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('let', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='glavna.let')),
                ('tip_karte', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='glavna.tipkarte')),
            ],
        ),
    ]
